@isTest
public class Tes_OrderSeikyuMeisai {

	static testMethod void testMethod_OrderSeikyuMeisai(){

		//TriggerIsActive__c customSetting = new TriggerIsActive__c(Name = 'defualt',isActive__c = true);
		//insert customSetting;

		//Account acc = new Account( Name = 'アカウントtest');
	 //   insert acc;
		
		//Date today = date.today();

		//Id   oppRdId    = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('シンプル安豪').getRecordTypeId();
		//Opportunity opp1 = new Opportunity(Name = '商談1', AccountId = acc.Id, RecordTypeId = oppRdId, StageName = 'フォロー',CloseDate = today);

  //   	insert opp1;

		//Opportunity opp2 = new Opportunity(Name = '商談2', AccountId = acc.Id, RecordTypeId = oppRdId, StageName = 'フォロー',CloseDate = today);

		//insert opp2;

		//Id rdId = Schema.SObjectType.OkyakusamaSeikyuMeisai__c.getRecordTypeInfosByName().get('請求子').getRecordTypeId();
		//OkyakusamaSeikyuMeisai__c okyakusamaSeikyuMeisai = new OkyakusamaSeikyuMeisai__c(OpportunityRef__c = opp1.Id,RecordTypeId = rdId);
		
		//insert okyakusamaSeikyuMeisai;

		//okyakusamaSeikyuMeisai.Kessaibi__c = today;

		//update okyakusamaSeikyuMeisai;

		//opp1.TorihikiShodanRef__c = opp2.Id;
		//update opp1;

		//delete okyakusamaSeikyuMeisai;
	}

	
}